### PR TITLE
Adapt to new squid

### PR DESCRIPTION
**Pull request by jreidinger**

### CODE REVIEW

**Comment by mvidner** [comment]
Thanks!
Have you tested it? If squid is stupid it could abort after reporting the 1st error so we may see a new obsolete tag after we submit this one.

**Comment by jreidinger** [comment]
no, I do not test it. Let me try it in VM

**Comment by jreidinger** [comment]
I did testing in SLE12SP1 and it works.

**Comment by mvidner** [comment]
LGTM!

**Pull request merged**
